#=============================================================================
# init.toml --- order make configuration for SpaceVim
# Author: Sineatos
#=============================================================================

# All SpaceVim option below [option] section
[options]
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = true

    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true

    filetree_direction = "left"

    # chinese vim help doc
    vim_help_language = "cn"

    # nerdtree instead of default vimfiler
    # show hidden file
    filemanager = "nerdtree"

    # setting formatter for java, download from (https://github.com/google/google-java-format)
    # layer_lang_java_formatter = "/home/sineatos/.tools/formatter/google-java-format-1.7-all-deps.jar"

[[layers]]
    name = 'core'
    filetree_show_hidden = true

# (+python3)
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "small"
  auto_completion_tab_key_behavior = "cycle"

[[layers]]
  name = "chinese"

[[layers]]
  name = "colorscheme"

# Fuzzy search (+python3)
[[layers]]
  name = "leaderf"

[[layers]]
  name = "git"

# apt install global
[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

# [[layers]]
#  name = "lang#java"

# need go tool chain && run :GoInstallBinaries
[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#sh"
